In [16]:
import pandas as pd
full_df = pd.read_csv("/Users/LeelaGangadhar/Desktop/INFO 7390 Advanced Data Sciences/Project/PythonNotebooks/train_short.csv")
length = len(full_df)
print(length)

#Splitting into train and test data
print(int(length*.8)) # 54130

train_df = full_df[0:54130]  # 80% training
test_df = full_df[54130:length] # 20% testing


67663
54130


In [17]:
print(train_df[0:1]) # NA is read as NaN

   customer_ID  shopping_pt  record_type  day   time state  location  \
0       140813            9            1    2  13:02    PA     37390   

   group_size  homeowner  car_age car_value  risk_factor  age_oldest  \
0           1          0       13         e          NaN          24   

   age_youngest  married_couple  C_previous  duration_previous  policy  cost  
0            24               0           1                  5       1   675  


In [18]:
# dropping columns with low co-coeff (6) including state, time, record_type, customer_ID, car_value and cost
# duration_previous, married_couple, day, group_size ,age_youngest, age_oldest  
train = train_df.drop(train_df.columns[[3, 7, 12, 13, 14, 16, 4, 5, 0, 2, 10, 18]], axis=1) 
test = test_df.drop(test_df.columns[[3, 7, 12, 13, 14, 16, 4, 5, 0, 2, 10, 18]], axis=1) 

In [19]:
train[0:1]

shopping_pt  location  homeowner  car_age  risk_factor  C_previous  policy
0            9     37390          0       13          NaN           1       1

In [20]:
test[0:1]

shopping_pt  location  homeowner  car_age  risk_factor  C_previous  \
54130            6     35653          0        9          NaN           4   

       policy  
54130       3

In [21]:
train["risk_factor"].mean()

2.56565308524995

In [22]:
train["C_previous"].mean()

2.4506604072356044

In [23]:
train["risk_factor"].count()

34827

In [24]:
train["C_previous"].count()

53679

In [25]:
train_df[0:5]

customer_ID  shopping_pt  record_type  day   time state  location  \
0       140813            9            1    2  13:02    PA     37390   
1       140815            6            1    3  13:41    FL     33166   
2       140809            7            1    4  14:45    PA     39166   
3       140811            6            1    1  12:42    RI     38272   
4       281617            7            1    2   9:47    IA     43903   

   group_size  homeowner  car_age car_value  risk_factor  age_oldest  \
0           1          0       13         e          NaN          24   
1           2          0        2         e            2          52   
2           1          1       20         d          NaN          51   
3           1          0       17         c            3          24   
4           1          0       12         e          NaN          55   

   age_youngest  married_couple  C_previous  duration_previous  policy  cost  
0            24               0           1                  5       1   675  
1            21               0           1                  6       4   653  
2            51               0           3                  1       1   620  
3            24               0           3                  8       3   661  
4            55               0           4                  4       3   595

In [26]:
car_value = train_df["car_value"]

In [27]:
len(car_value)

54130

In [28]:
# One-hot encoding
pd.get_dummies(car_value)[0:5]

a  b  c  d  e  f  g  h  i
0  0  0  0  0  1  0  0  0  0
1  0  0  0  0  1  0  0  0  0
2  0  0  0  1  0  0  0  0  0
3  0  0  1  0  0  0  0  0  0
4  0  0  0  0  1  0  0  0  0

In [35]:
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
# load the iris datasets
dataset = datasets.load_iris()
# fit a SVM model to the data
model = SVC()

train_na = train.dropna()
train_data = train_na["shopping_pt", "location", "homeowner", "car_age", "risk_factor", "C_previous"].values
train_target = train_na["policy"].values

model.fit(train_data, train_target)
print(model)
# make predictions
expected = train_target
predicted = model.predict(train_data)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KeyError: ('shopping_pt', 'location', 'homeowner', 'car_age', 'risk_factor', 'C_previous')

In [30]:
train_na[0:1]

shopping_pt  location  homeowner  car_age  risk_factor  C_previous  policy
1            6     33166          0        2            2           1       4

In [32]:
train_target = train_na["policy"]
type(train_target.values)

numpy.ndarray

In [34]:
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
# load the iris datasets
dataset = datasets.load_iris()
# fit a SVM model to the data
model = SVC()
type(dataset.data)

numpy.ndarray

In [38]:
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
# load the iris datasets
dataset = datasets.load_iris()
# fit a SVM model to the data
model = SVC()

train_na = train.dropna()
columns = ["shopping_pt", "location", "homeowner", "car_age", "risk_factor", "C_previous"]
train_data = train_na[columns].values
train_target = train_na["policy"].values

model.fit(train_data, train_target)
print(model)
# make predictions
expected = train_target
predicted = model.predict(train_data)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

test_na = test.dropna()
columns = ["shopping_pt", "location", "homeowner", "car_age", "risk_factor", "C_previous"]
test_data = test_na[columns].values
test_target = test_na["policy"].values

expected2 = test_target
predicted2 = model.predict(test_data)
# summarize the fit of the model
print(metrics.classification_report(expected2, predicted2))
print(metrics.confusion_matrix(expected2, predicted2))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
             precision    recall  f1-score   support

          1       0.99      0.99      0.99     12039
          2       0.97      0.93      0.95      8878
          3       0.92      0.99      0.95     12227
          4       1.00      0.56      0.72      1470

avg / total       0.96      0.96      0.95     34614

[[11918    22    99     0]
 [   37  8287   554     0]
 [   20   104 12103     0]
 [   44   168   436   822]]


In [39]:
test_na = test.dropna()
columns = ["shopping_pt", "location", "homeowner", "car_age", "risk_factor", "C_previous"]
test_data = test_na[columns].values
test_target = test_na["policy"].values

expected2 = test_target
predicted2 = model.predict(test_data)
# summarize the fit of the model
print(metrics.classification_report(expected2, predicted2))
print(metrics.confusion_matrix(expected2, predicted2))

             precision    recall  f1-score   support

          1       0.77      0.69      0.73      3038
          2       0.47      0.24      0.32      2154
          3       0.48      0.76      0.59      3142
          4       0.29      0.00      0.01       401

avg / total       0.57      0.57      0.55      8735

[[2091   78  868    1]
 [ 248  527 1377    2]
 [ 311  453 2376    2]
 [  49   60  290    2]]


In [75]:
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
# fit a SVM model to the data
model = KNeighborsClassifier(n_neighbors=6, weights='distance', algorithm='auto', leaf_size=30, p=1, metric='minkowski', 
                             metric_params=None, n_jobs=1) #SVC(max_iter=1000)

train_ = train.dropna()
train_na = train_.sample(frac=0.8,random_state=300)
columns = ["shopping_pt", "location", "homeowner", "car_age", "risk_factor", "C_previous"]
train_data = train_na[columns].values
train_target = train_na["policy"].values

model.fit(train_data, train_target)
print(model)
# make predictions
expected = train_target
predicted = model.predict(train_data)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
cm = metrics.confusion_matrix(expected, predicted)
print(metrics.accuracy_score(expected, predicted))

test_na = train_.drop(train_na.index)
columns = ["shopping_pt", "location", "homeowner", "car_age", "risk_factor", "C_previous"]
test_data = test_na[columns].values
test_target = test_na["policy"].values

expected2 = test_target
predicted2 = model.predict(test_data)
# summarize the fit of the model
print(metrics.classification_report(expected2, predicted2))
print(metrics.accuracy_score(expected2, predicted2))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=1,
           weights='distance')
             precision    recall  f1-score   support

          1       1.00      1.00      1.00      9596
          2       1.00      1.00      1.00      7182
          3       1.00      1.00      1.00      9754
          4       1.00      0.99      1.00      1159

avg / total       1.00      1.00      1.00     27691

0.99837492326
             precision    recall  f1-score   support

          1       0.74      0.77      0.75      2443
          2       0.45      0.41      0.43      1696
          3       0.55      0.61      0.58      2473
          4       0.15      0.04      0.06       311

avg / total       0.57      0.59      0.58      6923

0.591939910443


In [89]:
train_ = train.dropna()
train_na = train_.sample(frac=0.8,random_state=300)
test_na = train_.drop(train_na.index)
train_na_1 = train_na.loc[train_na['policy'] == 1]
train_na_2 = train_na.loc[train_na['policy'] == 2]
train_na_3 = train_na.loc[train_na['policy'] == 3]
train_na_4 = train_na.loc[train_na['policy'] == 4]

In [92]:
print(train_na_1.shape)
print(train_na_2.shape)
print(train_na_3.shape)
print(train_na_4.shape)

(9596, 7)
(7182, 7)
(9754, 7)
(1159, 7)


In [93]:
# Handling imbalanced classes
train_na_1 = train_na_1[0:1159]
train_na_2 = train_na_2[0:1159]
train_na_3 = train_na_3[0:1159]

frames = [train_na_1, train_na_2, train_na_3, train_na_4]
result = pd.concat(frames)

In [94]:
result.shape

(4636, 7)

In [108]:
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
# fit a SVM model to the data
model = SVC(max_iter=700)

train_ = result.dropna()
train_na = train_.sample(frac=0.8,random_state=300)
columns = ["shopping_pt", "location", "homeowner", "car_age", "risk_factor", "C_previous"]
train_data = train_na[columns].values
train_target = train_na["policy"].values

model.fit(train_data, train_target)
#print(model)
expected = train_target
predicted = model.predict(train_data)
# summarize the fit of the model
#print(metrics.classification_report(expected, predicted))
cm = metrics.confusion_matrix(expected, predicted)
print(metrics.accuracy_score(expected, predicted))

test_na = train_.drop(train_na.index)
columns = ["shopping_pt", "location", "homeowner", "car_age", "risk_factor", "C_previous"]
test_data = test_na[columns].values
test_target = test_na["policy"].values

expected2 = test_target
predicted2 = model.predict(test_data)
# summarize the fit of the model
#print(metrics.classification_report(expected2, predicted2))
print(metrics.accuracy_score(expected2, predicted2))

0.985171205177
0.361380798274


C:\Users\LeelaGangadhar\Anaconda3\lib\site-packages\sklearn\svm\base.py:224: ConvergenceWarning: Solver terminated early (max_iter=700).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


In [29]:
import numpy as np
import pandas as pd
full_df = pd.read_csv("train_short.csv")
# length = len(full_df)
# print(length)

# #Splitting into train and test data
# print(int(length*.8)) # 54130

# train_df = full_df[0:54130]  # 80% training
# test_df = full_df[54130:length] # 20% testing
# One-hot encoding
car_value = pd.get_dummies(full_df["car_value"])
policy = full_df["policy"].to_frame()
frames = [policy, car_value]

print(len(car_value))
print(len(policy))
result = pd.concat(frames, axis=1)
print(result[0:5])
print("Corr-Coef of policy to a :- ", np.corrcoef(result["policy"], result["a"])[0,1])
print("Corr-Coef of policy to b :- ", np.corrcoef(result["policy"], result["b"])[0,1])
print("Corr-Coef of policy to c :- ", np.corrcoef(result["policy"], result["c"])[0,1])
print("Corr-Coef of policy to d :- ", np.corrcoef(result["policy"], result["d"])[0,1])
print("Corr-Coef of policy to e :- ", np.corrcoef(result["policy"], result["e"])[0,1])
print("Corr-Coef of policy to f :- ", np.corrcoef(result["policy"], result["f"])[0,1])
print("Corr-Coef of policy to g :- ", np.corrcoef(result["policy"], result["g"])[0,1])
print("Corr-Coef of policy to h :- ", np.corrcoef(result["policy"], result["h"])[0,1])
print("Corr-Coef of policy to i :- ", np.corrcoef(result["policy"], result["i"])[0,1])


67663
67663
   policy  a  b  c  d  e  f  g  h  i
0       1  0  0  0  0  1  0  0  0  0
1       4  0  0  0  0  1  0  0  0  0
2       1  0  0  0  1  0  0  0  0  0
3       3  0  0  1  0  0  0  0  0  0
4       3  0  0  0  0  1  0  0  0  0
Corr-Coef of policy to a :-  -0.0218281003932
Corr-Coef of policy to b :-  -0.0345447123713
Corr-Coef of policy to c :-  -0.0853074370408
Corr-Coef of policy to d :-  -0.0400493213077
Corr-Coef of policy to e :-  -0.00729899221101
Corr-Coef of policy to f :-  0.0312978803974
Corr-Coef of policy to g :-  0.0425814075973
Corr-Coef of policy to h :-  0.0284457780611
Corr-Coef of policy to i :-  0.0149313106947


In [2]:
import fancyimpute
from fancyimpute import BiScaler, KNN, NuclearNormMinimization, SoftImpute


AttributeError: module 'cvxpy' has no attribute 'utilities'

In [19]:
import sklearn
from sklearn.preprocessing import Imputer
import numpy as np
import pandas as pd

full_df = pd.read_csv("numeric_train.csv")
print(full_df[0:3])
imp = Imputer(missing_values='NaN', strategy='knn', axis=0)
imp.fit(full_df)
imp_df = imp.transform(full_df)
print(imp_df[0:4])

   customer_ID  shopping_pt  record_type  day  time  state  location  \
0        14981            1            0    2     2     33     40588   
1        14981            2            0    2     2     33     40588   
2        14981            3            0    2     2     33     40588   

   group_size  homeowner  car_age  car_value  risk_factor  age_oldest  \
0           1          0       13          5          NaN          24   
1           1          0       13          5          NaN          24   
2           1          0       13          5          NaN          24   

   age_youngest  married_couple  C_previous  duration_previous  policy  cost  
0            24               0         NaN                NaN       1   677  
1            24               0         NaN                NaN       1   682  
2            24               0           1                  3       1   627  


ValueError: Can only use these strategies: ['mean', 'median', 'most_frequent']  got strategy=knn

In [1]:
import numpy as np
import pandas as pd

full_df = pd.read_csv("numeric_train.csv")
full_df[0:4]

customer_ID  shopping_pt  record_type  day  time  state  location  \
0        14981            1            0    2     2     33     40588   
1        14981            2            0    2     2     33     40588   
2        14981            3            0    2     2     33     40588   
3        14981            4            0    2     2     33     40588   

   group_size  homeowner  car_age  car_value  risk_factor  age_oldest  \
0           1          0       13          5          NaN          24   
1           1          0       13          5          NaN          24   
2           1          0       13          5          NaN          24   
3           1          0       13          5          NaN          24   

   age_youngest  married_couple  C_previous  duration_previous  policy  cost  
0            24               0         NaN                NaN       1   677  
1            24               0         NaN                NaN       1   682  
2            24               0           1                  3       1   627  
3            24               0           1                  3       1   634

In [13]:
import numpy as np
import pandas as pd
full_df = pd.read_csv("numeric_train.csv")
full_df_group = full_df.groupby(by=["customer_ID"]) # .agg(lambda x: )
columns_ = list(full_df.columns.values)
new_df = pd.DataFrame()
#print(new_df)
for grp, data in full_df_group :
#     if(int(grp) == 14981):
    x = list(data["C_previous"])
    z = x[len(x) - 1]
    p = list(data["duration_previous"])
    q = p[len(p) - 1]
    #grp_list = [grp]*len(x)
    #grp_df = pd.DataFrame(grp_list, columns=["customer_ID"])
    #print(grp_df)
    frames = [data.replace(to_replace={'C_previous' : {np.float64('nan') : z}, 'duration_previous' : {np.float64('nan') : q}})]
    result = pd.concat(frames, axis=1)
    #print(result)
    new_df = new_df.append(result)
    #break
    #print(new_df)
    #print(type(data.replace(to_replace={'C_previous' : {np.float64('nan') : z}}))) # , inplace=True

new_df[0:20]

    
# full_df1 = pd.DataFrame(full_df_group)
# full_df1[0:4]


KeyboardInterrupt: 

In [17]:
new_df[0:100]

customer_ID  shopping_pt  record_type  day  time  state  location  \
56157          217            1            0    2     1     25     30328   
56158          217            2            0    2     1     25     30328   
56159          217            3            0    2     1     25     30328   
56160          217            4            0    2     1     25     30328   
56161          217            5            0    2     1     25     30328   
56162          217            6            1    2     1     25     30328   
56132          233            1            0    2     2      2     30352   
56133          233            2            0    2     2      2     30352   
56134          233            3            0    2     2      2     30352   
56135          233            4            1    1     1      2     30352   
56232          245            1            0    2     1     22     30373   
56233          245            2            0    2     1     22     30373   
56234          245            3            0    2     1     22     30373   
56235          245            4            0    2     1     22     30373   
56236          245            5            0    2     1     22     30373   
56237          245            6            0    2     1     22     30373   
56238          245            7            0    2     1     22     30373   
56239          245            8            1    2     1     22     30373   
56225          253            1            0    2     2     11     30385   
56226          253            2            0    2     2     11     30385   
56227          253            3            0    2     2     11     30385   
56228          253            4            0    2     2     11     30385   
56229          253            5            0    2     2     11     30385   
56230          253            6            0    2     2     11     30385   
56231          253            7            1    2     2     11     30385   
56218          257            1            0    2     2     14     30391   
56219          257            2            0    2     2     14     30391   
56220          257            3            0    2     2     14     30391   
56221          257            4            0    2     2     14     30391   
56222          257            5            0    2     2     14     30391   
...            ...          ...          ...  ...   ...    ...       ...   
56354          275            7            1    2     1     22     30418   
56294          279            1            0    2     1     23     30424   
56295          279            2            0    2     1     23     30424   
56296          279            3            0    2     1     23     30424   
56297          279            4            0    2     2     23     30424   
56298          279            5            0    2     2     23     30424   
56299          279            6            0    2     2     23     30424   
56300          279            7            0    2     2     23     30424   
56301          279            8            0    2     2     23     30424   
56302          279            9            0    2     2     23     30424   
56303          279           10            0    2     2     23     30424   
56304          279           11            1    2     2     23     30424   
56305          283            1            0    2     2     32     30430   
56306          283            2            0    2     2     32     30430   
56307          283            3            0    2     2     32     30430   
56308          283            4            0    2     2     32     30430   
56309          283            5            0    2     2     32     30430   
56310          283            6            0    2     2     32     30430   
56311          283            7            1    2     2     32     30430   
56318          285            1            0    2     2     14     30433   
56319          285            2            0    2     2

In [6]:
# for grp, data in full_df_group :
#     if(int(grp) == 14981):
#         print(data)
#         break
type(full_df_group.get_group(14981))

pandas.core.frame.DataFrame

In [19]:
df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'))
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'))
df.append(df2)
df

A  B
0  1  2
1  3  4

In [21]:
import numpy as np
import pandas as pd
full_df = pd.read_csv("numeric_train.csv")
full_df_group = full_df.groupby(by=["customer_ID"], sort=False) # .agg(lambda x: )
df_list = []
pol_change = False
chan_shpt = 0
customer_id = []
change_lst = []
change_shpt_lst = []
policy_lst = []
cost_lst = []
#print(new_df)
for grp, data in full_df_group :
    temp_data = data
    #print(grp)
    x = list(data["C_previous"])
    p = list(data["cost"])
    q = list(data["policy"])
    cost_lst.append(p[len(x) - 1])
    policy_lst.append(q[len(q) - 1])
    z = x[len(x) - 1]
    #print(len(x))
    pol_previous = x[len(x) - 1] # final value of C_previous
    pol_change = 0 # didn't change
    change_shpt = 0
    for index,row in data.iterrows():
        if(row["C_previous"] == z):
            break
        else:
            pol_change = 1 # changed
            break
    if(pol_change == 1):
        #print(temp_data["C_previous"].count())
        pol = x[0]
        #print("initial policy", pol)
        for index,row in temp_data.iterrows():
            c = row["C_previous"]
            change_shpt = change_shpt + 1
            if(str(pol) != str(c)):
                break
       
    customer_id.append(grp)
    change_lst.append(pol_change)
    change_shpt_lst.append(change_shpt)
    #print(type(data.iterrows())) # generator
    #print(type(next(data.iterrows())))  # tuple
    #print((next(data.iterrows())[1])["customer_ID"] )
    #(next(data.iterrows())[1])["customer_ID"]
    #break

#print(df_list)
#print(len(customer_id))
#print((change_shpt_lst))
#result = pd.DataFrame({'customer_ID': customer_id, 'policy_change':change_lst, 'change_shpt':change_shpt_lst, 'policy': list(full_df['policy']), 'cost': list(full_df['cost'])})
result = pd.DataFrame({'customer_ID': customer_id, 'policy_change':change_lst, 'change_shpt':change_shpt_lst, 'policy': policy_lst, 'cost': cost_lst})
result[0:5]



change_shpt  cost  customer_ID  policy  policy_change
0            3   634        14981       1              1
1            5   703       261747       2              1
2            0   641        14987       3              0
3            0   664        14983       3              0
4            0   594       261745       1              0

In [24]:

print("Corr-Coef of policy to policy_change :- ", np.corrcoef(result["policy"], result["policy_change"])[0,1])
print("Corr-Coef of policy to change_shpt :- ", np.corrcoef(result["policy"], result["change_shpt"])[0,1])
print("Corr-Coef of cost to policy_change :- ", np.corrcoef(result["cost"], result["policy_change"])[0,1])
print("Corr-Coef of cost to change_shpt :- ", np.corrcoef(result["cost"], result["change_shpt"])[1,0])

# train_df = pd.read_csv("train_short.csv")
# result = pd.DataFrame({'customer_ID': customer_id, 'policy_change':change_lst, 'change_shpt':change_shpt_lst, 'policy': list(train_df['policy']), 'cost': list(train_df['cost'])})
#print(result.count())
#print(len(list(full_df['policy'])))
#result[0:100]

Corr-Coef of policy to policy_change :-  -0.00570757042782
Corr-Coef of policy to change_shpt :-  -0.00702158160607
Corr-Coef of cost to policy_change :-  0.0181114711012
Corr-Coef of cost to change_shpt :-  0.0243197715182


In [10]:
print("Corr-Coef of policy to policy_change :- ", np.corrcoef(result["policy"], result["policy_change"])[0,1])
print("Corr-Coef of policy to change_shpt :- ", np.corrcoef(result["policy"], result["change_shpt"])[0,1])
print("Corr-Coef of cost to policy_change :- ", np.corrcoef(result["cost"], result["policy_change"])[0,1])
print("Corr-Coef of cost to change_shpt :- ", np.corrcoef(result["cost"], result["change_shpt"])[0,1])

Corr-Coef of policy to policy_change :-  0.00532671187298
Corr-Coef of policy to change_shpt :-  0.00390845879472
Corr-Coef of cost to policy_change :-  -0.00589571063029
Corr-Coef of cost to change_shpt :-  -0.00139478821613


In [19]:
true = pd.read_csv("True-Labels-Results-dataset.csv")
predicted = pd.read_csv("Predicted-Labels.csv") # Predicted-Labels.csv
true_dict ={-0.19311990565834802: 1, 1.9026561774452901, 0.854768135893473:2, -1.2410079472101698}
print(set(list(true["policy"])))
print(set(list(predicted["Scored Labels"])))
# true_lst = list(true["policy"])

{-0.19311990565834802, 1.9026561774452901, 0.854768135893473, -1.2410079472101698}
{0.88322122205595599, 1.93867448209023, -0.17223203797831402, -1.2276852980125901}


In [13]:
import pandas as pd
dataFrame = pd.read_csv("train_short.csv")
dataFrame_1 = dataFrame.loc[dataFrame['policy'] == 1]
dataFrame_2 = dataFrame.loc[dataFrame['policy'] == 2]
dataFrame_3 = dataFrame.loc[dataFrame['policy'] == 3]
dataFrame_4 = dataFrame.loc[dataFrame['policy'] == 4]

count = len(dataFrame_4["policy"])

dataFrame_1 = dataFrame_1.sample(n = count, random_state = 10)
dataFrame_2 = dataFrame_2.sample(n = count, random_state = 100)
dataFrame_3 = dataFrame_3.sample(n = count, random_state = 1000)
dataFrame_final = dataFrame_1.append(dataFrame_2).append(dataFrame_3).append(dataFrame_4)



15700


15700

In [18]:
import numpy as np
dataFrame = pd.read_csv("train_short.csv")
rows = np.random.choice(dataFrame.index.values, count)
#sampled_df = dataFrame.ix[rows]
rows

dataFrame_1 = dataFrame.loc[dataFrame['policy'] == 1]
dataFrame_2 = dataFrame.loc[dataFrame['policy'] == 2]
dataFrame_3 = dataFrame.loc[dataFrame['policy'] == 3]
dataFrame_4 = dataFrame.loc[dataFrame['policy'] == 4]

count = len(dataFrame_4["policy"])
rows1 = np.random.choice(dataFrame_1.index.values, count)
rows2 = np.random.choice(dataFrame_2.index.values, count)
rows3 = np.random.choice(dataFrame_3.index.values, count)
rows4 = np.random.choice(dataFrame_4.index.values, count)

df_1 = dataFrame_1.ix[rows1]
df_2 = dataFrame_1.ix[rows2]
df_3 = dataFrame_1.ix[rows3]


dataFrame_final = df_1.append(df_2).append(df_3).append(dataFrame_4)


3925
3925
3925
15700


In [20]:
import matplotlib as mpl
import matplotlib.pyplot as plt
# import seaborn as sns
# sns.set()

import numpy as np
import itertools

from sklearn.datasets import make_classification
from sklearn.decomposition import PCA

from unbalanced_dataset import UnderSampler, NearMiss, CondensedNearestNeighbour, OneSidedSelection,\
NeighbourhoodCleaningRule, TomekLinks, ClusterCentroids, OverSampler, SMOTE,\
SMOTETomek, SMOTEENN, EasyEnsemble, BalanceCascade

dataFrame_1 = dataFrame.loc[dataFrame['policy'] == 1]
dataFrame_2 = dataFrame.loc[dataFrame['policy'] == 2]
dataFrame_3 = dataFrame.loc[dataFrame['policy'] == 3]
dataFrame_4 = dataFrame.loc[dataFrame['policy'] == 4]


# Generate the new dataset using under-sampling method
verbose = False
# 'Random under-sampling'
US = UnderSampler(verbose=verbose)
dataFrame_1_, dataFrame_2_, dataFrame_3_, dataFrame_4_ = US.fit_transform(dataFrame_1, dataFrame_2, dataFrame_3, dataFrame_4)


ImportError: No module named 'unbalanced_dataset'

In [39]:
import numpy as np
import pandas as pd
from datetime import datetime as dt
full_df = pd.read_csv("train.csv")
full_df_group = full_df.groupby(by=["customer_ID"], sort=False) # .agg(lambda x: )
df_list = []
pol_change = False
chan_shpt = 0
customer_id = []
change_lst = []
change_shpt_lst = []
policy_lst = []
cost_lst = []
time_diff = []
for grp, data in full_df_group :
    temp_data = data
    #print(grp)
    x = list(data["C_previous"])
    p = list(data["cost"])
    q = list(data["policy"])
    timeObj = []
    date_format = "%H:%M"
    t = list(data["time"])
    frst_time = dt.strptime(t[0], date_format)
    lst_time = dt.strptime(t[len(t) - 1], date_format)
    diff = lst_time - frst_time
    time_diff.append(int(diff.seconds / (60*60)))
    cost_lst.append(p[len(x) - 1])
    policy_lst.append(q[len(q) - 1])
    z = x[len(x) - 1]
    pol_previous = x[len(x) - 1] # final value of C_previous
    pol_change = 0 # didn't change
    change_shpt = 0
    for index,row in data.iterrows():
        if(row["C_previous"] == z):
            break
        else:
            pol_change = 1 # changed
            break
    if(pol_change == 1):
        pol = x[0]
        for index,row in temp_data.iterrows():
            c = row["C_previous"]
            change_shpt = change_shpt + 1
            if(str(pol) != str(c)):
                break
       
    customer_id.append(grp)
    change_lst.append(pol_change)
    change_shpt_lst.append(change_shpt)

result = pd.DataFrame({'customer_ID': customer_id, 'policy_change':change_lst, 'change_shpt':change_shpt_lst, 'policy': policy_lst, 'cost': cost_lst, 'time_diff': time_diff})

result.to_csv("session.csv")


In [37]:
print("Corr-Coef of policy to policy_change :- ", np.corrcoef(result["policy"], result["policy_change"])[0,1])
print("Corr-Coef of policy to change_shpt :- ", np.corrcoef(result["policy"], result["change_shpt"])[0,1])
print("Corr-Coef of cost to policy_change :- ", np.corrcoef(result["cost"], result["policy_change"])[0,1])
print("Corr-Coef of cost to change_shpt :- ", np.corrcoef(result["cost"], result["change_shpt"])[1,0])
print("Corr-Coef of policy to time_diff :- ", np.corrcoef(result["policy"], result["time_diff"])[0,1])
print("Corr-Coef of cost to time_diff :- ", np.corrcoef(result["cost"], result["time_diff"])[1,0])


Corr-Coef of policy to policy_change :-  -0.00570757042782
Corr-Coef of policy to change_shpt :-  -0.00702158160607
Corr-Coef of cost to policy_change :-  0.0181114711012
Corr-Coef of cost to change_shpt :-  0.0243197715182
Corr-Coef of policy to time_diff :-  0.00270160902845
Corr-Coef of cost to time_diff :-  -0.00289968187572


In [38]:
full_df1 = pd.read_csv("train_short.csv")
full_df1[0:5]

customer_ID  shopping_pt  record_type  day   time state  location  \
0       140813            9            1    2  13:02    PA     37390   
1       140815            6            1    3  13:41    FL     33166   
2       140809            7            1    4  14:45    PA     39166   
3       140811            6            1    1  12:42    RI     38272   
4       281617            7            1    2   9:47    IA     43903   

   group_size  homeowner  car_age car_value  risk_factor  age_oldest  \
0           1          0       13         e          NaN          24   
1           2          0        2         e            2          52   
2           1          1       20         d          NaN          51   
3           1          0       17         c            3          24   
4           1          0       12         e          NaN          55   

   age_youngest  married_couple  C_previous  duration_previous  policy  cost  
0            24               0           1                  5       1   675  
1            21               0           1                  6       4   653  
2            51               0           3                  1       1   620  
3            24               0           3                  8       3   661  
4            55               0           4                  4       3   595

In [40]:
full_df123 = pd.read_csv("session.csv")
full_df123[0:10]

change_shpt  cost  customer_ID  policy  policy_change  time_diff
0            3   634        14981       1              1         21
1            5   703       261747       2              1          4
2            0   641        14987       3              0          2
3            0   664        14983       3              0         16
4            0   594       261745       1              0          0
5            0   717       261771       4              0          0
6            0   655        14963       3              0          4
7            0   619       261773       2              0         22
8            0   657        14965       3              0          1
9            0   619       261767       3              0          0

In [3]:
import pandas as pd
import numpy as np
predicted = pd.read_csv("Policy Predictions.csv")
true = pd.read_csv("test_with_labels.csv")
pred_lst = list(predicted["policy"])
true_lst = list(true["policy"])
#print(len(pred_lst), len(true_lst))

# summarize the fit of the model
from sklearn import metrics
print(metrics.classification_report(true_lst, pred_lst))
print(metrics.confusion_matrix(true_lst, pred_lst))

29346 29346
             precision    recall  f1-score   support

          1       0.48      0.39      0.43      9487
          2       0.30      0.37      0.33      7277
          3       0.39      0.45      0.42     10875
          4       0.10      0.02      0.03      1707

avg / total       0.38      0.38      0.38     29346

[[3687 2068 3621  111]
 [1457 2696 3047   77]
 [2225 3697 4848  105]
 [ 300  573  801   33]]
